# Comprehensive Python Array Notes

This notebook covers arrays in Python, focusing on **lists** (Python's built-in array-like structure) and **NumPy arrays**. It includes all methods, operations, and advanced techniques for working with arrays, suitable for beginners and advanced users.

## Table of Contents
1. Python Lists as Arrays
   - Creation and Initialization
   - Accessing and Modifying Elements
   - List Methods
   - List Comprehension
   - Slicing and Indexing Tricks
2. NumPy Arrays
   - Installation and Setup
   - Creation and Initialization
   - Accessing and Modifying Elements
   - NumPy Array Methods and Attributes
   - Mathematical Operations
   - Broadcasting and Vectorization
   - Advanced Indexing and Slicing
3. Advanced Tricks and Tips
   - Memory Efficiency
   - Performance Optimization
   - Common Pitfalls
4. Practical Examples

---

## 1. Python Lists as Arrays

Python lists are dynamic, heterogeneous arrays that can store elements of different types. They are flexible but less efficient than NumPy arrays for numerical operations.

### 1.1 Creation and Initialization

In [ ]:
# Basic list creation
empty_list = []
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]

# Using list constructor
list_from_range = list(range(5))  # [0, 1, 2, 3, 4]
list_from_string = list("abc")    # ['a', 'b', 'c']

# Initialize with same value
zeros = [0] * 5  # [0, 0, 0, 0, 0]

print(numbers)
print(mixed)
print(list_from_range)
print(list_from_string)
print(zeros)

### 1.2 accessing and Modifying Elements

In [ ]:
# Accessing elements
numbers = [10, 20, 30, 40, 50]
print(numbers[0])      # 10 (first element)
print(numbers[-1])     # 50 (last element)

# Modifying elements
numbers[2] = 99
print(numbers)         # [10, 20, 99, 40, 50]

# Check if element exists
print(99 in numbers)   # True

# Length of list
print(len(numbers))    # 5

### 1.3 List Methods

Python lists have built-in methods for manipulation.

In [ ]:
lst = [1, 2, 3]

# append(x): Add element to end
lst.append(4)
print(lst)  # [1, 2, 3, 4]

# extend(iterable): Add all elements from iterable
lst.extend([5, 6])
print(lst)  # [1, 2, 3, 4, 5, 6]

# insert(i, x): Insert x at index i
lst.insert(2, 99)
print(lst)  # [1, 2, 99, 3, 4, 5, 6]

# remove(x): Remove first occurrence of x
lst.remove(99)
print(lst)  # [1, 2, 3, 4, 5, 6]

# pop([i]): Remove and return element at index i (default: last)
popped = lst.pop()
print(popped, lst)  # 6, [1, 2, 3, 4, 5]

# clear(): Remove all elements
lst.clear()
print(lst)  # []

# index(x): Return index of first x
lst = [1, 2, 3, 2]
print(lst.index(2))  # 1

# count(x): Count occurrences of x
print(lst.count(2))  # 2

# sort(): Sort list in-place
lst.sort()
print(lst)  # [1, 2, 2, 3]

# reverse(): Reverse list in-place
lst.reverse()
print(lst)  # [3, 2, 2, 1]

# copy(): Return shallow copy
lst_copy = lst.copy()
print(lst_copy)  # [3, 2, 2, 1]

### 1.4 List Comprehension

A concise way to create or transform lists.

In [ ]:
# Basic list comprehension
squares = [x**2 for x in range(5)]
print(squares)  # [0, 1, 4, 9, 16]

# With condition
evens = [x for x in range(10) if x % 2 == 0]
print(evens)  # [0, 2, 4, 6, 8]

# Nested list comprehension
matrix = [[i + j for j in range(3)] for i in range(3)]
print(matrix)  # [[0, 1, 2], [1, 2, 3], [2, 3, 4]]

### 1.5 Slicing and Indexing Tricks

In [ ]:
lst = [0, 1, 2, 3, 4, 5]

# Basic slicing: lst[start:end:step]
print(lst[1:4])    # [1, 2, 3]
print(lst[:3])     # [0, 1, 2]
print(lst[::2])    # [0, 2, 4]
print(lst[::-1])   # [5, 4, 3, 2, 1, 0] (reverse)

# Modify via slicing
lst[1:3] = [99, 98]
print(lst)  # [0, 99, 98, 3, 4, 5]

# Copy list
lst_copy = lst[:]
print(lst_copy)  # [0, 99, 98, 3, 4, 5]

## 2. NumPy Arrays

NumPy arrays are optimized for numerical operations and are more efficient than lists for large datasets.

### 2.1 Installation and Setup

In [ ]:
# Install NumPy (run in terminal or cell with !)
!pip install numpy

# Import NumPy
import numpy as np

### 2.2 Creation and Initialization

In [ ]:
# From list
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
# [[1 2 3]
#  [4 5 6]]

# Zeros, ones, and full
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)
print(zeros)
print(ones)
print(full)

# Range and linspace
arange = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # [0.  0.25 0.5  0.75 1. ]
print(arange)
print(linspace)

# Random arrays
random = np.random.rand(2, 3)  # Uniform [0, 1)
randint = np.random.randint(1, 10, (2, 3))  # Random integers
print(random)
print(randint)

### 2.3 Accessing and Modifying Elements

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])      # 10
print(arr[-1])     # 50

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[0, 1])  # 2

# Modify
arr[2] = 99
print(arr)  # [10 20 99 40 50]
arr_2d[1, 2] = 99
print(arr_2d)
# [[ 1  2  3]
#  [ 4  5 99]]

### 2.4 NumPy Array Methods and Attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape and size
print(arr.shape)   # (2, 3)
print(arr.size)    # 6
print(arr.ndim)    # 2

# Reshape
reshaped = arr.reshape(3, 2)
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

# Flatten
flat = arr.flatten()
print(flat)  # [1 2 3 4 5 6]

# Sum, mean, max, min
print(arr.sum())    # 21
print(arr.mean())   # 3.5
print(arr.max())    # 6
print(arr.min())    # 1

# Axis-wise operations
print(arr.sum(axis=0))  # [5 7 9] (sum of columns)
print(arr.sum(axis=1))  # [6 15] (sum of rows)

### 2.5 Mathematical Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a ** 2) # [1 4 9]

# Dot product
print(np.dot(a, b))  # 32 (1*4 + 2*5 + 3*6)

# Matrix multiplication
a_2d = np.array([[1, 2], [3, 4]])
b_2d = np.array([[5, 6], [7, 8]])
print(np.matmul(a_2d, b_2d))
# [[19 22]
#  [43 50]]

### 2.6 Broadcasting and Vectorization

NumPy allows operations on arrays of different shapes via broadcasting.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
print(arr * scalar)  # [[2 4 6]
                     #  [8 10 12]]

vector = np.array([1, 0, -1])
print(arr + vector)  # [[0 2 2]
                     #  [3 5 5]]

### 2.7 Advanced Indexing and Slicing

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Boolean indexing
print(arr[arr > 5])  # [6 7 8 9]

# Fancy indexing
rows = [0, 2]
cols = [1, 2]
print(arr[rows, cols])  # [2 9]

# Slicing
print(arr[:2, 1:])  # [[2 3]
                    #  [5 6]]

## 3. Advanced Tricks and Tips

### 3.1 Memory Efficiency
- Use NumPy arrays for large datasets as they are more memory-efficient than lists.
- Avoid unnecessary copies with `arr.view()` instead of `arr.copy()` when possible.

### 3.2 Performance Optimization
- Use vectorized operations instead of loops.
- Preallocate arrays with `np.zeros` or `np.empty` for large datasets.

In [ ]:
# Vectorized vs loop
import time

n = 1000000
lst = list(range(n))
arr = np.arange(n)

# Loop
start = time.time()
lst = [x * 2 for x in lst]
print("List loop time:", time.time() - start)

# Vectorized
start = time.time()
arr = arr * 2
print("NumPy vectorized time:", time.time() - start)

### 3.3 Common Pitfalls
- Lists are mutable; modifying a list affects all references.
- NumPy arrays are homogeneous; mixing types converts to a common type.
- Avoid nested lists for numerical computations; use NumPy instead.

## 4. Practical Examples

### Example 1: Matrix Transpose (List vs NumPy)

In [ ]:
# Using list comprehension
matrix = [[1, 2, 3], [4, 5, 6]]
transpose = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print(transpose)

# Using NumPy
arr = np.array(matrix)
print(arr.T)

### Example 2: Normalize an Array

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)  # [0.  0.25 0.5  0.75 1. ]

### Example 3: Find Duplicates

In [ ]:
# Using list
lst = [1, 2, 2, 3, 3, 4]
duplicates = [x for x in set(lst) if lst.count(x) > 1]
print(duplicates)  # [2, 3]

# Using NumPy
arr = np.array(lst)
unique, counts = np.unique(arr, return_counts=True)
duplicates_np = unique[counts > 1]
print(duplicates_np)  # [2 3]